// {
// 	"cols":
//      {
// 	  	     "name":
// 	  	    "state":
// 	  	    "lga":
// 	    }               ,
export default [
  {
    name: 'Yobe',
    state: 'San José',
    lga: 'Alajuelita',
  },
  {
    name: 'Yobe',
    state: 'CA',
    lga: "L'Hospitalet de Llobregat",
  },
  {
    name: 'Yobe',
    state: 'British Columbia',
    lga: 'Tumbler Ridge',
  },
  {
    name: 'Yobe',
    state: 'MG',
    lga: 'Divinópolis',
  },
  {
    name: 'Yobe',
    state: 'ARK',
    lga: 'Koryazhma',
  },
  {
    name: 'Yobe',
    state: 'Gaziantep',
    lga: 'Gaziantep',
  },
  {
    name: 'Yobe',
    state: 'AR',
    lga: 'Huesca',
  },
  {
    name: 'Yobe',
    state: 'RM',
    lga: 'San Miguel',
  },
  {
    name: 'Yobe',
    state: 'BE',
    lga: 'Berlin',
  },
  {
    name: 'Yobe',
    state: 'ID',
    lga: 'Nampa',
  },
  {
    name: 'Yola',
    state: 'Victoria',
    lga: 'Belgrave',
  },
  {
    name: 'Yola',
    state: 'ON',
    lga: 'Oxford County',
  },
  {
    name: 'Yola',
    state: 'Arequipa',
    lga: 'Arequipa',
  },
  {
    name: 'Yola',
    state: 'G',
    lga: 'Cañas',
  },
  {
    name: 'Yola',
    state: 'Nordrhein-Westphalen',
    lga: 'Köln',
  },
  {
    name: 'Yola',
    state: 'Veracruz',
    lga: 'Minatitlán',
  },
  {
    name: 'Yola',
    state: 'PE',
    lga: 'Tenby',
  },
  {
    name: 'Yola',
    state: 'Hgo',
    lga: 'Pachuca',
  },
  {
    name: 'Yola',
    state: 'VT',
    lga: 'Colchester',
  },
  {
    name: 'Yola',
    state: 'Ulster',
    lga: 'Belfast',
  },
  {
    name: 'Kebbi',
    state: 'Hamburg',
    lga: 'Hamburg',
  },
  {
    name: 'Kebbi',
    state: 'OV',
    lga: 'Denderbelle',
  },
  {
    name: 'Kebbi',
    state: 'Veneto',
    lga: 'Castelbaldo',
  },
  {
    name: 'Kebbi',
    state: 'Gyeonggi',
    lga: 'Incheon',
  },
  {
    name: 'Kebbi',
    state: 'New South Wales',
    lga: 'Wagga Wagga',
  },
  {
    name: 'Kebbi',
    state: 'San José',
    lga: 'Patalillo',
  },
  {
    name: 'Kebbi',
    state: 'Vienna',
    lga: 'Vienna',
  },
  {
    name: 'Kebbi',
    state: 'ANT',
    lga: 'Rionegro',
  },
  {
    name: 'Kebbi',
    state: 'Extremadura',
    lga: 'Badajoz',
  },
  {
    name: 'Kebbi',
    state: 'JB',
    lga: 'Bekasi',
  },
  {
    name: 'Lagos',
    state: 'San Luis Potosí',
    lga: 'San Luis Potosí',
  },
  {
    name: 'Lagos',
    state: 'C',
    lga: 'Galway',
  },
  {
    name: 'Lagos',
    state: 'Ist',
    lga: 'Istanbul',
  },
  {
    name: 'Lagos',
    state: 'Ancash',
    lga: 'Chimbote',
  },
  ['Lagos', 'ON', 'Ottawa'],
  ['Lagos', 'LA', 'Lafayette'],
  ['Lagos', 'Junín', 'Huancayo'],
  ['Lagos', 'Texas', 'Houston'],
  ['Lagos', 'Heredia', 'Mercedes'],
  ['Lagos', 'IV', 'Coquimbo'],
  ['Kano', 'Tarapacá', 'Iquique'],
  ['Kano', 'Jeo', 'Jeongeup'],
  ['Kano', 'Sonora', 'Nogales'],
  ['Kano', 'Tambov Oblast', 'Tambov'],
  ['Kano', 'BL', 'Khuzdar'],
  ['Kano', 'KPK', 'Mansehra'],
  ['Kano', 'Central Java', 'Semarang'],
  ['Kano', 'Zl', 'Terneuzen'],
  ['Kano', 'Antioquia', 'Bello'],
  ['Kano', 'HE', 'Frankfurt am Main'],
  ['Yobe', 'CA', "L'Hospitalet de Llobregat"],
  ['Yobe', 'Aquitaine', 'Périgueux'],
  ['Yobe', 'Mexico City', 'Mexico City'],
  ['Yobe', 'Noord Holland', 'Naarden'],
  ['Yobe', 'QC', 'Malartic'],
  ['Yobe', 'Lubuskie', 'Gorzów Wielkopolski'],
  ['Yobe', 'CH', 'Chester'],
  ['Yobe', 'Andhra Pradesh', 'Karimnagar'],
  ['Yobe', 'JB', 'Bandung'],
  ['Yobe', 'ARE', 'Arequipa'],
  ['Yola', 'TUL', 'Tula'],
  ['Yola', 'LAZ', 'Mazzano Romano'],
  ['Yola', 'PK', 'Mielec'],
  ['Yola', 'RM', 'San José de Maipo'],
  ['Yola', 'KI', 'Balikpapan'],
  ['Yola', 'Gyeonggi', 'Gwangju'],
  ['Yola', 'AN', 'Córdoba'],
  ['Yola', 'Alaska', 'College'],
  ['Yola', 'AB', 'Turriff'],
  ['Yola', 'Metropolitana de Santiago', 'Estación Central'],
  ['Kebbi', 'X', 'Ockelbo'],
  ['Kebbi', 'Hessen', 'Dreieich'],
  ['Kebbi', 'Stockholms län', 'Lidingo'],
  ['Kebbi', 'Nord-Pas-de-Calais', 'Roubaix'],
  ['Kebbi', 'New South Wales', 'Penrith'],
  ['Kebbi', 'Västra Götalands län', 'Kungälv'],
  ['Kebbi', 'Jeo', 'Jeonju'],
  ['Kebbi', 'L.', 'Paal'],
  ['Kebbi', 'Île-de-France', 'Boulogne-Billancourt'],
  ['Kebbi', 'HH', 'Hamburg'],
  ['Lagos', 'CO', 'Lakewood'],
  ['Lagos', 'Vienna', 'Vienna'],
  ['Lagos', 'South Island', 'Alexandra'],
  ['Lagos', 'Gl', 'Apeldoorn'],
  ['Lagos', 'Istanbul', 'Istanbul'],
  ['Lagos', 'JI', 'Dutse'],
  ['Lagos', 'ANT', 'Bello'],
  ['Lagos', 'Balochistan', 'Washuk'],
  ['Lagos', 'Lambayeque', 'Lambayeque'],
  ['Lagos', 'Mazowieckie', 'Warszawa'],
  ['Kano', 'Ontario', 'Norfolk County'],
  ['Kano', 'C', 'Galway'],
  ['Kano', 'WA', 'Nedlands'],
  ['Kano', 'Uttar Pradesh', 'Varanasi'],
  ['Kano', 'AN', 'Málaga'],
  ['Kano', 'Anglesey', 'Holyhead'],
  ['Kano', 'NW', 'Essen'],
  ['Kano', 'Małopolskie', 'Kraków'],
  ['Kano', 'Jigawa', 'Dutse'],
  ['Kano', 'New South Wales', 'Newcastle'],
];
